#define TAPPING_TERM 175
#define TAPPING_TOGGLE 2
#define TAPPING_FORCE_HOLD_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY
#define DYNAMIC_TAPPING_TERM_INCREMENT 10
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
