#define TAPPING_TERM 175
#define TAPPING_TOGGLE 2
#define TAPPING_FORCE_HOLD_PER_KEY
#define PERMISSIVE_HOLD
#define DYNAMIC_TAPPING_TERM_INCREMENT 10
// #define CHORDAL_HOLD
#define FLOW_TAP_TERM 150
