#pragma once

#undef MANUFACTURER
#define MANUFACTURER "Bryan"
#undef PRODUCT
#define PRODUCT "Lily58"

#define MASTER_RIGHT

#undef RGBLIGHT_LED_COUNT
#define RGBLIGHT_LED_COUNT 24
#define RGBLED_SPLIT { 12, 12 }

#define RGBLIGHT_SLEEP

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 10
#define RGBLIGHT_VAL_STEP 10
