AUDIO_ENABLE = no
AUTO_SHIFT_ENABLE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
#LEADER_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE= yes
# OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = yes
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
SWAP_HANDS_ENABLE = no

CONVERT_TO=kb2040

#DYNAMIC_TAPPING_TERM_ENABLE = yes
SRC += fryguy.c
